apiVersion: v2
name: common
description: A Library Helm Chart for grouping common logic
type: library
version: 0.2.0
appVersion: "0.2.0"
dependencies:
- name: common
  version: 1.11.1
  repository: https://charts.bitnami.com/bitnami
