apiVersion: v2
name: common
description: A Library Helm Chart for grouping common logic
type: library
version: 1.1.0
appVersion: "1.1.0"
dependencies:
- name: common
  version: 2.0.3
  repository: https://charts.bitnami.com/bitnami
