apiVersion: v2
name: blackbox-monitoring
description: Blackbox monitoring with Prometheus, Alertmanager and Grafana
type: application
version: 0.1.1
appVersion: 0.1.0
dependencies:
- name: common
  version: 1.1.0
  repository: https://sun-asterisk-research.github.io/helm-charts
- name: prometheus
  version: 15.16.1
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus.enabled
- name: prometheus-blackbox-exporter
  version: 7.1.2
  repository: https://prometheus-community.github.io/helm-charts
  alias: blackbox-exporter
- name: grafana
  version: 6.43.0
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled
