apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
subsets:
- addresses:
  {{- range .Values.remoteIPs }}
  - ip: {{ . }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.remotePort }}
    protocol: TCP
