apiVersion: v2
name: redis-ha
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: common
  version: 0.2.0
  repository: https://sun-asterisk-research.github.io/helm-charts
- name: redis
  version: 15.3.1
  repository: https://charts.bitnami.com/bitnami
