{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "redis-ha.serviceAccountName" . }}-haproxy
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: haproxy
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
