apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
data:
  DB_HOST: {{ index .Values .Values.dbType "host" | quote }}
  DB_PORT: {{ index .Values .Values.dbType "port" | quote }}
