apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-script
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  init-db.sql: |
    {{- tpl (.Files.Get (printf "scripts/%s-init.sql" .Values.dbType)) . | nindent 4 }}
