apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  DB_HOST: {{ index .Values .Values.dbType "host" | b64enc | quote }}
  DB_PORT: {{ index .Values .Values.dbType "port" | toString | b64enc | quote }}
  DB_USERNAME: {{ index .Values .Values.dbType "username" | b64enc | quote }}
  DB_PASSWORD: {{ index .Values .Values.dbType "password" | b64enc | quote }}
  {{- if eq .Values.dbType "postgresql" }}
  DB_DATABASE: {{ .Values.postgresql.database | b64enc | quote }}
  {{- end }}
