apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.dbType "mysql" }}
  MYSQL_ROOT_USER: {{ .Values.mysql.rootUser | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc | quote }}
  {{- else if eq .Values.dbType "postgresql" }}
  POSTGRESQL_POSTGRES_PASSWORD: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  {{- end }}
