apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "common.names.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ include "deployer.role.kind" . }}
  name: {{ include "deployer.role.name" . }}
