apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openedx.fullname" . }}-openedx-settings-cms
  labels:
    {{- include "openedx.labels" . | nindent 4 }}
data:
  __init__.py: |
{{ tpl (.Files.Get "settings/cms/__init__.py") . | indent 4 }}

  development.py: |
{{ tpl (.Files.Get "settings/cms/development.py") . | indent 4 }}

  production.py: |
{{ tpl (.Files.Get "settings/cms/production.py") . | indent 4 }}

  test.py: |
{{ tpl (.Files.Get "settings/cms/test.py") . | indent 4 }}
    