{{- if and .Values.subscribers.redis.enabled (empty .Values.subscribers.redis.passwordSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-redis
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.subscribers.redis.password | b64enc }}
{{- end -}}
