{{- if .Values.subscribers.http.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-clients
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- $clients := list -}}
  {{- range .Values.subscribers.http.clients -}}
  {{- $clients = append $clients (printf "{ \"appId\": \"%s\", \"key\": \"%s\" }" .appId .key)  -}}
  {{- end }}
  laravel-echo-server.json: |
    {
      "clients": [
        {{ join ",\n" $clients }}
      ]
    }
{{- end -}}
