{{- if .Values.prometheus.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  prometheus.yml: |-
    {{- tpl (.Files.Get "prometheus/prometheus.yml.gotmpl") . | nindent 4 }}
  {{- range $path, $_ := .Files.Glob "prometheus/rules/**.gotmpl" }}
  {{ base $path | trimSuffix ".gotmpl" }}: |-
    {{- tpl ($.Files.Get $path) $ | nindent 4 }}
  {{- end }}
{{- end -}}
