{{- if .Values.ingress.enabled -}}
{{- $fullName := include "common.names.fullname" . -}}
apiVersion: {{ template "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
  {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
  {{- end }}
  {{- if and .Values.ingress.ingressClassName (eq "false" (include "common.ingress.supportsIngressClassname" .)) }}
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName | quote }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.ingressClassName (include "common.ingress.supportsIngressClassname" .) }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
        pathType: {{ .pathType | default "ImplementationSpecific" }}
        {{- end }}
        backend: {{- include "common.ingress.backend" (dict "serviceName" $fullName "servicePort" "http" "context" $) | nindent 10 }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.host | quote }}
    secretName: {{ printf "%s-tls" .Values.ingress.host }}
  {{- end }}
{{- end -}}
