apiVersion: v2
name: openedx
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
- name: minio
  version: 6.1.1
  repository: https://charts.bitnami.com/bitnami
  condition: minio.enabled
- name: mongodb
  version: 10.6.1
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled
- name: mariadb
  version: 9.3.2
  repository: https://charts.bitnami.com/bitnami
  condition: mysql.enabled
  alias: mysql
- name: redis
  version: 12.7.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
