nameOverride: ""
fullnameOverride: ""

commonLabels: {}

commonAnnotations: {}

image:
  registry: docker.io
  pullPolicy: IfNotPresent
  pullSecrets: []

debug: false

dbType: mysql

mysql:
  image:
    repository: bitnami/mysql
    tag: 8.0.30-debian-11-r7
  host: localhost
  port: 3306
  username: root
  password: ""
  sslMode: preferred
  authPlugin: mysql_native_password

postgresql:
  image:
    repository: bitnami/postgresql
    tag: 14.2.0-debian-10-r73
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: ""
  sslMode: prefer

extraArgs: []

extraEnvVars: []

users: []
# - username:
#   password:
#   forcePassword: false

databases: {}
  # mydatabase:
  #   ownner: mydatabase_owner
  #   readonly:
  #   - mydatabase_reader
  #   readwrite:
  #   - mydatabase_writer
  #   extensions:
  #   - pg_stat_statements
