apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-gateway
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: gateway
    spec:
      serviceAccountName: {{ include "codecov.serviceAccountName" . }}
      {{- include "codecov.imagePullSecrets" . | nindent 6 }}
      containers:
      - name: codecov-gateway
        image: {{ template "codecov.images.gateway" . }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        env:
          - name: CODECOV_GATEWAY_MINIO_ENABLED
            value: "false"
          - name: CODECOV_API_HOST
            value: {{ include "common.names.fullname" . }}-api
          - name: CODECOV_API_PORT
            value: {{ .Values.api.service.port | quote }}
          - name: CODECOV_API_SCHEME
            value: http
          - name: CODECOV_IA_HOST
            value: {{ include "common.names.fullname" . }}-api
          - name: CODECOV_IA_PORT
            value: {{ .Values.api.service.port | quote }}
          - name: CODECOV_IA_SCHEME
            value: http
          - name: CODECOV_DEFAULT_HOST
            value: {{ include "common.names.fullname" . }}-frontend
          - name: CODECOV_DEFAULT_PORT
            value: {{ .Values.frontend.service.port | quote }}
          - name: CODECOV_DEFAULT_SCHEME
            value: http
          - name: CODECOV_GATEWAY_HTTP_PORT
            value: "8080"
          {{- if .Values.minio.enabled }}
          - name: CODECOV_MINIO_HOST
            value: {{ include "common.names.fullname" . }}-minio
          - name: CODECOV_MINIO_PORT
            value: {{ .Values.minio.service.ports.api | quote }}
          {{- end }}
          {{- with .Values.extraEnvs }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        envFrom:
          {{- include "codecov.env" . | nindent 8 }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /gateway_health
            port: http
        readinessProbe:
          httpGet:
            path: /gateway_health
            port: http
        {{- if .Values.gateway.containerSecurityContext.enabled }}
        securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.gateway.containerSecurityContext "context" $) | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.gateway.resources | nindent 12 }}
      volumes:
      {{- include "codecov.volumes" . | nindent 6 }}
      {{- if .Values.gateway.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.gateway.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.gateway.podAffinityPreset "component" "gateway" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.gateway.podAntiAffinityPreset "component" "gateway" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" .Values.gateway.nodeAffinityPreset | nindent 10 }}
      {{- end }}
      {{- if .Values.gateway.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.gateway.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.gateway.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.gateway.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.gateway.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.gateway.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.gateway.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.gateway.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
