apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  SETUP__ENTERPRISE_LICENSE: {{ .Values.config.setup.enterprise_license | b64enc | quote }}
  SETUP__HTTP__COOKIE_SECRET: {{ .Values.config.setup.http.cookie_secret | b64enc | quote }}
  GITHUB__CLIENT_ID: {{ .Values.config.github.client_id | b64enc | quote }}
  GITHUB__CLIENT_SECRET: {{ .Values.config.github.client_secret | b64enc | quote }}
  GITHUB__GLOBAL_UPLOAD_TOKEN: {{ .Values.config.github.global_upload_token | b64enc | quote }}
  GITHUB__WEBHOOK_SECRET: {{ .Values.config.github.webhook_secret | b64enc | quote }}
  GITHUB__INTEGRATION__ID: {{ .Values.config.github.integration.id | toString | b64enc | quote }}
  GITHUB__INTEGRATION__PEM: {{ .Values.config.github.integration.pem | b64enc | quote }}
  SERVICES__REDIS_URL: {{ include "codecov.redis.url" .  | b64enc | quote }}
  SERVICES__DATABASE_URL: {{ include "codecov.db.url" . | b64enc | quote }}
  {{- if and .Values.timescaledb.enabled .Values.config.setup.timeseries.enabled }}
  SERVICES__TIMESERIES_DATABASE_URL: {{ include "codecov.db.timescaleUrl" . | b64enc | quote }}
  {{- end }}
  {{- if .Values.minio.enabled }}
  SERVICES__MINIO__HOST: {{ printf "%s-minio" (include "common.names.fullname" .) | b64enc | quote }}
  SERVICES__MINIO__PORT: {{ .Values.minio.service.ports.api | toString | b64enc | quote }}
  SERVICES__MINIO__BUCKET: "codecov"
  SERVICES__MINIO__REGION: "us-east-1"
  SERVICES__MINIO__ACCESS_KEY_ID: {{ .Values.minio.auth.rootUser | b64enc | quote }}
  SERVICES__MINIO__SECRET_ACCESS_KEY: {{ .Values.minio.auth.rootPassword | b64enc | quote }}
  {{- else }}
  SERVICES__MINIO__HOST: {{ .Values.config.services.minio.host | b64enc | quote }}
  SERVICES__MINIO__PORT: {{ .Values.config.services.minio.port | toString | b64enc | quote }}
  SERVICES__MINIO__BUCKET: {{ .Values.config.services.minio.bucket | b64enc | quote }}
  SERVICES__MINIO__REGION: {{ .Values.config.services.minio.region | b64enc | quote }}
  SERVICES__MINIO__VERIFY_SSL: {{ .Values.config.services.minio.verifySsl | toString | b64enc | quote }}
  SERVICES__MINIO__ACCESS_KEY_ID: {{ .Values.config.services.minio.accessKeyId | b64enc | quote }}
  SERVICES__MINIO__SECRET_ACCESS_KEY: {{ .Values.config.services.minio.secretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.gitlab_enterprise }}
  GITLAB_ENTERPRISE__URL: {{ .Values.config.gitlab_enterprise.url | b64enc | quote }}
  GITLAB_ENTERPRISE__CLIENT_ID: {{ .Values.config.gitlab_enterprise.clientId | b64enc | quote }}
  GITLAB_ENTERPRISE__CLIENT_SECRET: {{ .Values.config.gitlab_enterprise.clientSecret | b64enc | quote }}
  GITLAB_ENTERPRISE__SSL_PEM: {{ .Values.config.gitlab_enterprise.sslPem | default "" | b64enc | quote }}
  {{- end }}
