{{- if not (empty .Values.config.github.intergration) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-secret-files
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  {{- range $filename, $content := .Values.secretFiles }}
  {{ $filename }}: {{ $content | b64enc | quote }}
  {{- end }}
{{- end }}
