apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-frontend-svc
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend