{{- if .Values.forum.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "openedx.fullname" . }}-forum
  labels:
    {{- include "openedx.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openedx.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: forum
  template:
    metadata:
      labels:
        {{- include "openedx.labels" . | nindent 8 }}
        app.kubernetes.io/component: forum
    spec:
      containers:
        - name: {{ template "openedx.fullname" . }}-forum
          image: docker.io/overhangio/openedx-forum:11.1.3
          ports:
            - containerPort: 4567
          env:
            - name: SEARCH_SERVER
              value: "http://{{ include "openedx.fullname" . }}-elasticsearch:{{ .Values.elasticsearch.service.port }}"
            - name: MONGODB_AUTH
              value: "{{ if and .Values.mongodb.auth.username .Values.mongodb.auth.password }}{{ .Values.mongodb.auth.username }}:{{ .Values.mongodb.auth.password }}@{{ end }}"
            - name: MONGODB_HOST
              value: {{ include "openedx.mongodb.host" . }}
            - name: MONGODB_PORT
              value: {{ include "openedx.mongodb.port"  . | quote }}
            - name: MONGOID_AUTH_MECH
              value: ":scram"
      initContainers:
        - name: init-es
          image: docker.io/overhangio/openedx-forum:11.1.3
          env:
            - name: SEARCH_SERVER
              value: "http://{{ include "openedx.fullname" . }}-elasticsearch:{{ .Values.elasticsearch.service.port }}"
            - name: MONGODB_AUTH
              value: "{{ if and .Values.mongodb.auth.username .Values.mongodb.auth.password }}{{ .Values.mongodb.auth.username }}:{{ .Values.mongodb.auth.password }}@{{ end }}"
            - name: MONGODB_HOST
              value: {{ include "openedx.mongodb.host" . }}
            - name: MONGODB_PORT
              value: {{ include "openedx.mongodb.port" . | quote }}
            - name: MONGOID_AUTH_MECH
              value: ":scram"
          args:
          - bash
          - -c
          - |
            echo $SEARCH_SERVER
            echo $MONGODB_AUTH
            echo $MONGODB_HOST
            echo $MONGODB_PORT
            bundle exec rake search:initialize --trace
            bundle exec rake search:rebuild_index --trace
{{- end }}
