apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openedx.fullname" . }}-openedx-config
  labels: 
    {{- include "openedx.labels" . | nindent 4 }}
data:
  cms.env.json: |
{{ tpl (.Files.Get "config/cms.env.json") . | indent 4 }}

  lms.env.json: |    
{{ tpl (.Files.Get "config/lms.env.json") . | indent 4 }}
