kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "openedx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "openedx.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "openedx.fullname" . }}
