apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "openedx.fullname" . }}
  labels:
    {{- include "openedx.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      