apiVersion: v2
name: image-pull-secret
description: Secret for pulling private docker images
type: application
version: 0.1.0
dependencies:
- name: common
  version: 0.2.0
  repository: https://sun-asterisk-research.github.io/helm-charts
